services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  main-site:
    build:
      context: ./frontend/main-site
    container_name: nextjs_main_site
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend/main-site:/app
      - /app/node_modules

    working_dir: /app
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    command: sh -c "npm install && npm run dev"

    depends_on:
      - backend

  admin-panel:
    build:
      context: ./frontend/admin-panel
    container_name: react_dmin_panel
    ports:
      - 3001:3001
    restart: always
    volumes:
      - ./frontend/admin-panel:/app
      - /app/node_modules
      
    working_dir: /app
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    command: sh -c "npm install && npm run dev"

    depends_on:
      - main-site

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: